### ISSUE TITLE
Disable or cloak usernames in affilate frontend reports

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/pmpro-affiliates#11]
As for privacy reasons (some users use mail addresses as usernames) there should be an option to remove or cloak the user information (who bought a membership) from the frontend reports.

**Comment by kimcoleman** [comment]
This is possible using the shortcode attributes we have just documented here: https://www.paidmembershipspro.com/add-ons/pmpro-lightweight-affiliate-tracking/#report
