### ISSUE TITLE
Repeat checkout not tracked if done from different device

### ISSUE THREAD

**Issue by GeorgiSK** [strangerstudios/pmpro-affiliates#12]
I have a setup where all my levels are not reccurring and they have expiration periods.
I tried registering a new account with an affiliate code from an existing account and the affiliate was tracked.
Then i tried to change my level from this new account from the same pc where i registered with the affiliate code and it was still fine, i was able to see the new payment in the affiliates page of the original account.

Then when i tried to change the membership again from the second account but on a different device (one that doesn't have the cookie set), the order was not processed as an affiliate order, im not able to see it in the affiliates page of the first account nor in the admin panel. Also checked the database and it seems that the affiliate_id field is not set for this particular order.

I think that an extension is required, that will make sure that the first time when a cookie is detected, a new column is added to the users table, which column contains the affiliate code the user has registered with. And on subsequent transactions, if the cookie is not present or no longer valid, this field will be checked and the order awarded to the referrer that has this code

**Comment by kimcoleman** [comment]
At this time the Lightweight Affiliates Add On does not function in this way and requires the cookie be present at checkout to award the referral. You could write a custom function that would hook into the pmpro_after_checkout (https://www.paidmembershipspro.com/hook/pmpro_after_checkout/) or pmpro_added_order (https://www.paidmembershipspro.com/hook/pmpro_added_order/) hook that references the previous order for the user. This section of the code shows how the affiliate is tracked for a subscription when the last order has an affiliate ID attached: https://github.com/strangerstudios/pmpro-affiliates/blob/dev/pmpro-affiliates.php#L174-L186
