### ISSUE TITLE
BUG: Recurring orders may not continue to be tracked for affiliate

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-affiliates#14]
`pmpro_affiliates_pmpro_added_order()` runs on `pmpro_added_order` hook, so after the order is added to the database.

It looks like this code should get the affiliate for previous orders in the subscription, but the SQL query gets the most recent order, which is the one that was just added, so it will never find an affiliate:
https://github.com/strangerstudios/pmpro-affiliates/blob/d1e2dfc6c04411f08f334af1b29f48b862b77a95/pmpro-affiliates.php#L175-L186

Suggested fix is to update the SQL query to find any order for that user with an identical subscription ID to the order being added that also has a non-empty affiliate. This should also make this excerpt of code MMPU-compatible.

**Comment by dparker1005** [comment]
Support ticket (admins only): https://www.paidmembershipspro.com/forums/topic/affiliates-lightweight-affiliate-tracking-how-does-it-handle-trial-periods/

**Comment by MaryOJob** [comment]
User asked what are the options available for tracking recurring payments.

Support ticket (admins only): https://www.paidmembershipspro.com/forums/topic/affiliate-tracking-on-subscriptions/
