### ISSUE TITLE
User suggest fix in code

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-affiliates#16]
The notation utf8 should not be written directly.
/ ** Database Charset to use in creating database tables. * /
define (‘DB_CHARSET’, ‘utf8mb4’);
As the number of users who define ut8mb4 is increasing like this, I think it is better to use the value of DB_CHARSET.

https://www.paidmembershipspro.com/forums/topic/recommendation-for-fixing-source-code-for-pmpro-affiliates/

**Comment by kimcoleman** [comment]
I don't see anywhere in this Add On's code that sets a database character set. Do you have a link to where this code is set?

**Comment by ideadude** [comment]
Found it here: https://github.com/strangerstudios/pmpro-affiliates/blob/96dba9a2ac232f82c4b58542237d669eeaec0b8c/pmpro-affiliates.php#L98

Fixed here https://github.com/strangerstudios/pmpro-affiliates/commit/48f33f2bbcbf3020cd533e9b24e539b9f00ed723
