### ISSUE TITLE
Feature Request: add a filter for affiliate codes generated.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-affiliates#22]
Should we consider adding a filter for the `pmpro_affiliates_getNewCode` function that will allow customization of the users affiliate code?

**Comment by ipokkel** [comment]
PR: https://github.com/strangerstudios/pmpro-affiliates/pull/23

**Comment by kimcoleman** [comment]
Done in https://github.com/strangerstudios/pmpro-affiliates/pull/25
