### ISSUE TITLE
Shortcode is not working.

### ISSUE THREAD

**Issue by stunomatic** [strangerstudios/pmpro-affiliates#3]
Hello, 
Thank for this great membership plugin. 

[pmpro_affiliate_report]

http://centreforachievement.com/affiliates/

 I'm working here but this shortcode is not working I also installed affiliation plugin and I can easily generate affiliation code too but its not working on pages.. 

Please check 

Thank ou

**Comment by jaredtm13** [comment]
When going to the page I created with the shortcode, I get redirected to the membership-account page with no reports. Any ideas?

**Comment by jasonq007** [comment]
I got redirected to the membership-account page with no reports too, although I uploaded report.php into pages folder.

**Comment by kimcoleman** [comment]
The Affiliates Report page as assigned under Memberships > Settings > Page Settings and containing the [pmpro_affiliates_report] shortcode can only be viewed if you are an active Affiliate. Make sure you have assigned yourself an Affiliate account under Memberships > Affiliates before you attempt to access the page.
