### ISSUE TITLE
Adding this string `&pa=marypmpro` returns a "page not found"

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-affiliates#31]
**Describe the bug**
The  and (&) `&pa=marypmpro` string returns a page not found both on local and live sites. Using the question mark string `?pa=marypmpro` works as intended.

**To Reproduce**
1. Activate PMPro Affiliates Add On
2. Add new affiliate
3. copy the affiliate link and replace `?` with the `&`  string and add to any page on your site or homepage
4. See error " Page Not Found"

**Screenshots**
<img width="869" alt="Screen Shot 2021-03-09 at 9 41 59 PM" src="https://user-images.githubusercontent.com/25005583/110535305-60eccb80-8120-11eb-8988-3fdbfcaebdae.png">

**Expected behavior**
The `&` string should work as stated on our front end Affiliates reports page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin and PMPro Affiliates Add On is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress version - 5.6.2
PHP version - 7.4.14
Paid Memberships Pro - 2.5.6
PMPro Affiliates Add On - 0.4.1
```
</details>

**Comment by ZebulanStanphill** [comment]
This is not a bug. Query strings **must** start with a question mark. It's part of the standard internet URI format. See [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3). Presumably, an `&` prior to the first `?` would be interpreted as part of the page path, hence the "Page Not Found" you're seeing.
