### ISSUE TITLE
Duplicate orders in affiliate mode

### ISSUE THREAD

**Issue by vincenzocasu** [strangerstudios/pmpro-affiliates#32]
Why if an order comes from an affiliation is there a need to create a duplicate order with an amount equal to 0?

https://github.com/strangerstudios/pmpro-affiliates/blob/769a00e71a4a8e2b2520fefb5e63419f096333a4/pmpro-affiliates.php#L249

**Comment by kimcoleman** [comment]
We require an order to track the Affiliate conversion. By default, Paid Memberships Pro will not always create a $0 order for a new membership level, and the conversion tracking an affiliate crediting here tracks against orders (membership checkouts.

**Comment by kimcoleman** [comment]
The system should not be creating duplicate orders, only an order in the event that no other orders were added at checkout.
