### ISSUE TITLE
Add Hook for Custom Code to Add Columns to the Admin Tables

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-affiliates#33]
**Is your feature request related to a problem? Please describe.**
We want to keep this plugin as lightweight as possible. Specifically, we do not have any plans to add the concept of a commission percentage or a calculation of someone's payouts.

We could, though, add a hook so custom code can add columns to the tables in the admin for the "Manage Affiliates" screen or the "Reports" screen. 

Users could then add a custom admin-only field using Register Helper OR set a sitewide default based on the level of the conversion. Then use this new hook to show the affiliate's rate on the all view, and a calculated commission on the report view.

**Describe the solution you'd like**
Add a hook to the "Manage Affiliates" screen and the "Reports" screen for the header row, and each data row. We also need to account for the report export to CSV and include this data in that export. 

The approach will be similar to these hooks on the core PMPro Discount Codes screens: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/discountcodes.php#L791 and https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/discountcodes.php#L955

And this filter for the CSV Orders Export: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/orders-csv.php#L349

Once we code this, let's include writing up the recipe to add additional columns to show the Affiliate's referral rate (pulled from a site global fixed rate in the recipe) and on the report screen, a calculation of the affiliate payout for the referral.

Question: should we consider a hook on the frontend output of the shortcode, too, so that sites can show the commission there?

**Comment by JarrydLong** [comment]
Attaching screenshots here for reference 

![image](https://user-images.githubusercontent.com/8989542/150966241-cb7676e1-fd16-4ce1-8cfe-68febf43864e.png)

![image](https://user-images.githubusercontent.com/8989542/150972150-1b2e7e4a-50e6-4307-bf62-8be47d070999.png)
