### ISSUE TITLE
PMPRO and Affiliates Pro

### ISSUE THREAD

**Issue by delbrab** [strangerstudios/pmpro-affiliates#5]
I have installed both affiliates pro, Pmpro and the woocommerce integrated plugin
I have membership levels

Upon check out, the systems records the new member and their subscription
however, it does not record for affiliates pro the membership and the amount they are due
Do I need to create products that are identified as membership in woocommerce products
in order for affiliates pro to record the values of the memberships?

Under woocommerce I do not have products defined
only memberships in membership pro and the correct pages associated with them.
thanks

**Comment by kimcoleman** [comment]
This Lightweight Affiliate Tracking Add On is only compatible with the Paid Memberships Pro checkout process at this time. It may be that you are using Post Affiliates Pro, another affiliate plugin that is not the same as this one.
